In [8]:
###Solution = https://docs.google.com/document/d/1QCnnupiJXQdMzv1E1Q8Y8EZ54-McyhOIKh1WFMi-yR0/edit
import pandas as pd

pos_df = pd.read_csv('data/pos_examples_PosSentiment.txt', header = None, names = ['text'], sep = '\n')
neg_df = pd.read_csv('data/neg_examples_NegSentiment.txt', header = None, names = ['text'], sep = '\n')

pos_df
neg_df

text
0   @chief1972 not with my iPhone 1st generation I...
1   @mandeev I can't go today.  Give them my love\...
2   Ugh\nHad some awesome unknown Belgian beer ton...
3   Told Fizul that 2 of my friends are coming. To...
4                            Disturbed by White Light
5                            Working on this fine day
6   needs to see the boy so he can take away all t...
7                                   Sickly  goodnight
8   Good morning driven w/out my ipod.  so sad. Bu...
9   heyyy where'd my tweet go?  *shouts to @fusebo...
10                               Oh no! Bill is dead!
11  @ilovemakonnen damnit u just ruined the image ...
12                                Working until 230am
13                         has really bad headaches..
14  watching Taylor Swift videos from YouTube on m...
15  @sobeworld the 0 calorie ones are hard 2 find;...
16  @itsjudytime ur so lucky!! I love summer!! unl...
17           I missed the call from my boo.  Sad face
18  bedtimeee tomorrow prepearing for the last wee...
19                     I'm going to miss my apartment
20  Weekends almost over  if only the weekdays wen...
21  everyone please vote for @selenagomez for teen...
22  At work... Meeting tonight but I'm kinda out o...
23   batting average after today 538 befour today 600
24  Chris Brown is scum ...  justice failed once a...
25             @CeCeaKaDiMpLeZ don't sound so excited
26            disappointed the didnt win teh glasses.
27  @katiehutchison It hasn't been quite that long...
28  Lloonngg asss dayy and its no where near over ...
29  Watching my 13 year ild brother-in-law's baseb...
30           sick  just hung out with cousins all day
31  @ceskaholka Wow. four days! I get migraines fr...
32                               Awww  @ColeTheCondor
33  This train is taking so long. It stops at stat...
34  Ow my eyes hurt from staring at this screen fo...
35  @tylercaulfield no fevers\nNose piercing got h...
36  @Meg_Andruschak What?! Still no baby?  I hope ...
37                                3.0 broke my iPhone
38  wishing i could go back in time and go to texa...
39  Geez....... hockey is over with till October. ...
40                          may head to bed try sleep
41  Time for some much needed sleep\nthe boo says ...
42  being sad about losing followers..i be oh so b...
43  @Kristofer_Krack Oh man! You can't punish ME f...
44  @Shesirawr @evvss pmnya baca aja  http://myloc...
45                I don't think i like twitter so far
46  7 games to 0 Mancala ass beating administered ...
47  Next will be English class for kindy.  I wish ...
48                       I wanted orange chicken too!
49  @KezzieN you're not the only one.Here my MTV d...
50  Boyfriend was all sad and gloomy last night.al...
51  I am enjoying my time here but missing my husb...
52                I had a really long scary nightmare
53  @PatrickAvis Stretching and rest\n@disobedient...
54  @moregAAn I know... It just makes me sad. Who'...
55  @jen_n_em The link sends me to my Fb home page...
56  OMGGGG havent tweeted for so long  id just lik...
57  @Dragonrider80 sounds painfull poor thing  yea...
58  just found that last fm is no longer free radi...
59  @nicholasbraun atleast you get to sleep all da...
                                                  ...

[50080 rows x 1 columns]

In [9]:
len(pos_df)

50064

In [10]:
test_neg = pd.read_csv('data/neg_examples_NegSentiment.txt', header = None, names = ['text'], sep = ',')

In [11]:
test_neg

text
0   @chief1972 not with my iPhone 1st generation I...
1   @mandeev I can't go today.  Give them my love\...
2   Ugh\nHad some awesome unknown Belgian beer ton...
3   Told Fizul that 2 of my friends are coming. To...
4                            Disturbed by White Light
5                            Working on this fine day
6   needs to see the boy so he can take away all t...
7                                   Sickly  goodnight
8   Good morning driven w/out my ipod.  so sad. Bu...
9   heyyy where'd my tweet go?  *shouts to @fusebo...
10                               Oh no! Bill is dead!
11  @ilovemakonnen damnit u just ruined the image ...
12                                Working until 230am
13                         has really bad headaches..
14  watching Taylor Swift videos from YouTube on m...
15  @sobeworld the 0 calorie ones are hard 2 find;...
16  @itsjudytime ur so lucky!! I love summer!! unl...
17           I missed the call from my boo.  Sad face
18  bedtimeee tomorrow prepearing for the last wee...
19                     I'm going to miss my apartment
20  Weekends almost over  if only the weekdays wen...
21  everyone please vote for @selenagomez for teen...
22  At work... Meeting tonight but I'm kinda out o...
23   batting average after today 538 befour today 600
24  Chris Brown is scum ...  justice failed once a...
25             @CeCeaKaDiMpLeZ don't sound so excited
26            disappointed the didnt win teh glasses.
27  @katiehutchison It hasn't been quite that long...
28  Lloonngg asss dayy and its no where near over ...
29  Watching my 13 year ild brother-in-law's baseb...
30           sick  just hung out with cousins all day
31  @ceskaholka Wow. four days! I get migraines fr...
32                               Awww  @ColeTheCondor
33  This train is taking so long. It stops at stat...
34  Ow my eyes hurt from staring at this screen fo...
35  @tylercaulfield no fevers\nNose piercing got h...
36  @Meg_Andruschak What?! Still no baby?  I hope ...
37                                3.0 broke my iPhone
38  wishing i could go back in time and go to texa...
39  Geez....... hockey is over with till October. ...
40                          may head to bed try sleep
41  Time for some much needed sleep\nthe boo says ...
42  being sad about losing followers..i be oh so b...
43  @Kristofer_Krack Oh man! You can't punish ME f...
44  @Shesirawr @evvss pmnya baca aja  http://myloc...
45                I don't think i like twitter so far
46  7 games to 0 Mancala ass beating administered ...
47  Next will be English class for kindy.  I wish ...
48                       I wanted orange chicken too!
49  @KezzieN you're not the only one.Here my MTV d...
50  Boyfriend was all sad and gloomy last night.al...
51  I am enjoying my time here but missing my husb...
52                I had a really long scary nightmare
53  @PatrickAvis Stretching and rest\n@disobedient...
54  @moregAAn I know... It just makes me sad. Who'...
55  @jen_n_em The link sends me to my Fb home page...
56  OMGGGG havent tweeted for so long  id just lik...
57  @Dragonrider80 sounds painfull poor thing  yea...
58  just found that last fm is no longer free radi...
59  @nicholasbraun atleast you get to sleep all da...
                                                  ...

[50082 rows x 1 columns]

In [283]:
##### load training data
import random
import numpy as np
import pandas as pd

###read tagged sentiment Tweets
with open('data/pos_examples_PosSentiment.txt', 'r') as f:
    pos_tweets = f.readlines()

with open('data/neg_examples_NegSentiment.txt', 'r') as f:
    neg_tweets = f.readlines()
    
class_label = 0
train_pos = pd.DataFrame(pos_tweets, columns = ['text'])
X0 = train_pos.text
y0 = np.full(shape=len(X0), fill_value=class_label)

###create random 80-20 split
rows = random.sample(X0.index, int(0.8*len(X0)))
X0_80 = X0.ix[rows]
X0_20 = X0.drop(rows)
y0_80 = y0[:int(0.8*len(X0))]
y0_20 = y0[int(0.8*len(X0)):]
###

class_label = 1
train_neg = pd.DataFrame(neg_tweets, columns = ['text'])
X1 = train_neg.text
y1 = np.full(shape=len(X1), fill_value=class_label)

###create random 80-20 split
rows = random.sample(X1.index, int(0.8*len(X1)))
X1_80 = X1.ix[rows]
X1_20 = X1.drop(rows)
y1_80 = y1[:int(0.8*len(X1))]
y1_20 = y1[int(0.8*len(X1)):]
###

X_train = pd.concat((X0_80,X1_80))
y_train = np.concatenate((y0_80, y1_80))

X_holdout = pd.concat((X0_20,X1_20))
y_holdout = np.concatenate((y0_20, y1_20))

### load testing data

###read tagged sentiment Tweets
with open('data/pos_examples_happy.txt', 'r') as f:
    pos_tweets = f.readlines()

with open('data/neg_examples_sad.txt', 'r') as f:
    neg_tweets = f.readlines()
    
import numpy as np
class_label = 0
train_pos = pd.DataFrame(pos_tweets, columns = ['text'])
X0 = train_pos.text
y0 = np.full(shape=len(X0), fill_value=class_label)

class_label = 1
train_neg = pd.DataFrame(neg_tweets, columns = ['text'])
X1 = train_neg.text
y1 = np.full(shape=len(X1), fill_value=class_label)

X_test = pd.concat((X0,X1))
y_test = np.concatenate((y0, y1))

###
print "Loading data = COMPLETE!"

Loading data = COMPLETE!


In [197]:
### build pipeline; fit train; predict on test
import nltk
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.linear_model.logistic import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

##vectorizer arguments blah!

tokenizer=None#word_tokenize
stop_words=nltk.corpus.stopwords.words("english")#None
ngram_range=(1, 3)
lowercase=True
max_features=5000
binary=False
dtype=np.float64
    
###create vectorizer
vectorizer = CountVectorizer(decode_error="ignore",
#                                tokenizer=tokenizer,
                               stop_words=stop_words,
                               ngram_range=ngram_range,
                               lowercase=lowercase,
                               binary=binary,
                               dtype=dtype,
                               max_features=max_features)

###create pipeline
text_clf = Pipeline([
                     ('vect', vectorizer),
#                      ('tfidf', TfidfTransformer()),
                     ('clf', MultinomialNB(alpha=0.01)),
#                     ('clf', LinearSVC(C=0.1)),
#                     ("clf", LogisticRegression(fit_intercept=False))
#         ("clf", RandomForestClassifier(n_estimators=50, max_features="auto", criterion="entropy", n_jobs=-1)),
                    ])

###fit training data
# text_clf = text_clf.fit(X_train, y_train)

### predict on test data
# predicted = text_clf.predict(X_test)
# np.mean(predicted == y_test)

print "Building pipeline = DONE!"

Building pipeline = DONE!


In [284]:
###fit training data
text_clf = text_clf.fit(X_train, y_train)
print "Fitting on train data = DONE!"

Fitting on train data = DONE!


In [201]:
###evaluate model on holdout set and print confusion matrix
predicted = text_clf.predict(X_holdout)
print np.mean(predicted == y_holdout)

from sklearn.metrics import accuracy_score, confusion_matrix
print "Predict on holdout data = DONE!"
total_confusion_matrix = confusion_matrix(y_holdout, predicted)

0.729125
Predict on holdout data = DONE!


In [216]:
###get performance metrics
# accuracy = np.mean(y_holdout == predicted)
accuracy = (y_holdout,predicted)
precision, recall, fscore, sup = precision_recall_fscore_support(y_holdout, predicted, average='binary', pos_label=0)
print precision, recall, fscore, accuracy

0.731591448931 0.7238 0.727674868676 0.729125


In [208]:
tp = total_confusion_matrix[0][0]
fn = total_confusion_matrix[0][1]
fp = total_confusion_matrix[1][0]
tn = total_confusion_matrix[1][1]

tp, fn, fp, tn

(14476, 5524, 5311, 14689)

In [211]:
precision = float(tp)/(tp+fp)
recall = float(tp)/(tp+fn)
accuracy = float(tp+tn)/(tp+tn+fp+fn)
fscore = 2.0*precision*recall/(precision+recall)
precision, recall, accuracy, fscore

(0.7315914489311164, 0.7238, 0.729125, 0.7276748686756981)

In [83]:
text_clf

Pipeline(steps=[('vect', CountVectorizer(analyzer=u'word', binary=False, decode_error='ignore',
        dtype=<type 'numpy.float64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=5000, min_df=1,
        ngram_range=(1, 3), preprocessor=None,
        stop_words=['i', '...enizer=None, vocabulary=None)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [175]:
## predict on test data and print confusion matrix
predicted = text_clf.predict(X_test)
print np.mean(predicted == y_test)

from sklearn.metrics import accuracy_score, confusion_matrix
print "Predict on test data = DONE!"
confusion_matrix(y_test, predicted)

0.952987598647
Predict on test data = DONE!


array([[17305,   435],
       [ 1233, 16507]])

In [166]:
#### 5-fold cross-validation: NB
import numpy as np
from sklearn.cross_validation import KFold

total_confusion_matrix = np.zeros((2, 2))
count = 0

kf = KFold(len(X_train), n_folds=5, shuffle=True, random_state=42)
for train, test in kf:
    ##split into cv- train and test:
    count += 1
    print "Fold ", count 
    X_CVtrain, y_CVtrain, X_CVtest, y_CVtest = X_train.values[train], y_train[train], X_train.values[test], y_train[test]
    
    ###fit on cv-train:
    cv = text_clf.fit(X_CVtrain, y_CVtrain)

    ## predict on cv-test
    predicted = cv.predict(X_CVtest)
    
    ###get confusion matric
    from sklearn.metrics import accuracy_score, confusion_matrix
    current_confusion_matrix = confusion_matrix(y_CVtest, predicted)
    print current_confusion_matrix
    print "Accuracy = ", np.mean(y_CVtest == predicted)
    total_confusion_matrix += current_confusion_matrix

print "FINAL CONFUSION MATRIX"
print total_confusion_matrix

Fold  1
[[11591  4283]
 [ 4317 11809]]
Accuracy =  0.73125
Fold  2
[[11231  4909]
 [ 3806 12054]]
Accuracy =  0.72765625
Fold  3
[[11433  4470]
 [ 4256 11841]]
Accuracy =  0.7273125
Fold  4
[[11050  5079]
 [ 3777 12094]]
Accuracy =  0.72325
Fold  5
[[11529  4425]
 [ 4336 11710]]
Accuracy =  0.72621875
FINAL CONFUSION MATRIX
[[ 56834.  23166.]
 [ 20492.  59508.]]


In [176]:
#### 5-fold cross-validation: SVC
import numpy as np
from sklearn.cross_validation import KFold

total_confusion_matrix = np.zeros((2, 2))
count = 0

kf = KFold(len(X_train), n_folds=5, shuffle=True, random_state=42)
for train, test in kf:
    ##split into cv- train and test:
    count += 1
    print "Fold ", count 
    X_CVtrain, y_CVtrain, X_CVtest, y_CVtest = X_train.values[train], y_train[train], X_train.values[test], y_train[test]
    
    ###fit on cv-train:
    cv = text_clf.fit(X_CVtrain, y_CVtrain)

    ## predict on cv-test
    predicted = cv.predict(X_CVtest)
    
    ###get confusion matric
    from sklearn.metrics import accuracy_score, confusion_matrix
    current_confusion_matrix = confusion_matrix(y_CVtest, predicted)
    print current_confusion_matrix
    print "Accuracy = ", np.mean(y_CVtest == predicted)
    total_confusion_matrix += current_confusion_matrix

print "FINAL CONFUSION MATRIX"
print total_confusion_matrix

Fold  1
[[11373  4501]
 [ 4269 11857]]
Accuracy =  0.7259375
Fold  2
[[11230  4910]
 [ 3860 12000]]
Accuracy =  0.7259375
Fold  3
[[11490  4413]
 [ 4271 11826]]
Accuracy =  0.728625
Fold  4
[[11173  4956]
 [ 3740 12131]]
Accuracy =  0.72825
Fold  5
[[11527  4427]
 [ 4304 11742]]
Accuracy =  0.72715625
FINAL CONFUSION MATRIX
[[ 56793.  23207.]
 [ 20444.  59556.]]


In [188]:
#Confusion matrix =  [ tp fn]
#                    [ fp tn]
tp = total_confusion_matrix[0][0]
fn = total_confusion_matrix[0][1]
fp = total_confusion_matrix[1][0]
tn = total_confusion_matrix[1][1]

precision = tp/(tp+fp)
recall = tp/(tp+fn)
accuracy = (tp+tn)/(tp+tn+fp+fn)
fscore = 2*precision*recall/(precision+recall)

In [185]:
total_confusion_matrix

array([[ 56793.,  23207.],
       [ 20444.,  59556.]])

In [186]:
tp, fp, tn, fn

(56793.0, 20444.0, 59556.0, 23207.0)

In [189]:
precision, recall, accuracy, fscore

(0.73530820720639067, 0.70991249999999995, 0.72718125, 0.72238722438102987)

In [190]:
from sklearn.metrics import precision_recall_fscore_support


In [195]:
precision_recall_fscore_support(y_CVtest, predicted, average='binary')

(0.72620446533490013, 0.73177115792097724, 0.72897718454136284, None)

In [193]:
y_CVtest

array([ 0.,  0.,  0., ...,  1.,  1.,  1.])

In [194]:
predicted

array([ 0.,  0.,  0., ...,  1.,  0.,  0.])

5524

In [225]:
### build pipeline; fit train; predict on holdout - MNB, SVC, RF
import nltk
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.linear_model.logistic import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

##vectorizer arguments blah!

tokenizer=None#word_tokenize
stop_words=nltk.corpus.stopwords.words("english")#None
ngram_range=(1, 3)
lowercase=True
max_features=5000
binary=False
dtype=np.float64
    
###create vectorizer
vectorizer = CountVectorizer(decode_error="ignore",
#                                tokenizer=tokenizer,
                               stop_words=stop_words,
                               ngram_range=ngram_range,
                               lowercase=lowercase,
                               binary=binary,
                               dtype=dtype,
                               max_features=max_features)

##set best parameters
alpha = 0.1
C = 1.0
n_estimators = 100
##

classif = "MNB"
print "Multinomial NB - holdout"

###create pipeline
text_clf = Pipeline([
                     ('vect', vectorizer),
#                      ('tfidf', TfidfTransformer()),
                     ('clf', MultinomialNB(alpha=alpha)),
#                     ('clf', LinearSVC(C=0.1)),
#                     ("clf", LogisticRegression(fit_intercept=False))
#         ("clf", RandomForestClassifier(n_estimators=50, max_features="auto", criterion="entropy", n_jobs=-1)),
                    ])

###fit training data
text_clf = text_clf.fit(X_train, y_train)

### predict on test data
predicted = text_clf.predict(X_holdout)

###get performance metrics
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
accuracy = accuracy_score(y_holdout,predicted)
#         accuracy = np.mean(y_CVtest == predicted)
precision, recall, fscore, sup = precision_recall_fscore_support(y_holdout, predicted, average='binary', pos_label=0)
print classif, precision, recall, fscore, accuracy# np.mean(predicted == y_test)

###

classif = "LinearSVC"
print "LinearSVC - holdout"

###create pipeline
text_clf = Pipeline([
                     ('vect', vectorizer),
#                      ('tfidf', TfidfTransformer()),
#                      ('clf', MultinomialNB(alpha=alpha)),
                    ('clf', LinearSVC(C=C)),
#                     ("clf", LogisticRegression(fit_intercept=False))
#         ("clf", RandomForestClassifier(n_estimators=50, max_features="auto", criterion="entropy", n_jobs=-1)),
                    ])

###fit training data
text_clf = text_clf.fit(X_train, y_train)

### predict on test data
predicted = text_clf.predict(X_holdout)

###get performance metrics
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
accuracy = accuracy_score(y_holdout,predicted)
#         accuracy = np.mean(y_CVtest == predicted)
precision, recall, fscore, sup = precision_recall_fscore_support(y_holdout, predicted, average='binary', pos_label=0)
print classif, precision, recall, fscore, accuracy# np.mean(predicted == y_test)
###

classif = "randomforest"
print "RandomForest - holdout"

###create pipeline
text_clf = Pipeline([
                     ('vect', vectorizer),
#                      ('tfidf', TfidfTransformer()),
#                      ('clf', MultinomialNB(alpha=alpha)),
#                     ('clf', LinearSVC(C=C)),
#                     ("clf", LogisticRegression(fit_intercept=False))
        ("clf", RandomForestClassifier(n_estimators=n_estimators, max_features="auto", criterion="entropy", n_jobs=-1)),
                    ])

###fit training data
text_clf = text_clf.fit(X_train, y_train)

### predict on test data
predicted = text_clf.predict(X_holdout)

###get performance metrics
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
accuracy = accuracy_score(y_holdout,predicted)
#         accuracy = np.mean(y_CVtest == predicted)
precision, recall, fscore, sup = precision_recall_fscore_support(y_holdout, predicted, average='binary', pos_label=0)
print classif, precision, recall, fscore, accuracy# np.mean(predicted == y_test)
###
print "Prediction on holdout = DONE!"

Multinomial NB - holdout
MNB 0.728148036708 0.726 0.727072431837 0.727475
LinearSVC - holdout
LinearSVC 0.71397616468 0.7908 0.750427026001 0.737
RandomForest - holdout
randomforest 0.725082146769 0.7613 0.742749823166 0.736325
Prediction on holdout = DONE!


In [226]:
### build pipeline; fit TRAIN; predict on TEST - MNB, SVC, RF
import nltk
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.linear_model.logistic import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

##vectorizer arguments blah!

tokenizer=None#word_tokenize
stop_words=nltk.corpus.stopwords.words("english")#None
ngram_range=(1, 3)
lowercase=True
max_features=5000
binary=False
dtype=np.float64
    
###create vectorizer
vectorizer = CountVectorizer(decode_error="ignore",
#                                tokenizer=tokenizer,
                               stop_words=stop_words,
                               ngram_range=ngram_range,
                               lowercase=lowercase,
                               binary=binary,
                               dtype=dtype,
                               max_features=max_features)

##set best hyperparameters
alpha = 0.1
C = 1.0
n_estimators = 100
##

classif = "MNB"
print "Multinomial NB - Test"

###create pipeline
text_clf = Pipeline([
                     ('vect', vectorizer),
#                      ('tfidf', TfidfTransformer()),
                     ('clf', MultinomialNB(alpha=alpha)),
#                     ('clf', LinearSVC(C=0.1)),
#                     ("clf", LogisticRegression(fit_intercept=False))
#         ("clf", RandomForestClassifier(n_estimators=50, max_features="auto", criterion="entropy", n_jobs=-1)),
                    ])

###fit training data
text_clf = text_clf.fit(X_train, y_train)

### predict on test data
predicted = text_clf.predict(X_test)

###get performance metrics
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
accuracy = accuracy_score(y_test,predicted)
#         accuracy = np.mean(y_CVtest == predicted)
precision, recall, fscore, sup = precision_recall_fscore_support(y_test, predicted, average='binary', pos_label=0)
print classif, precision, recall, fscore, accuracy# np.mean(predicted == y_test)

###

classif = "LinearSVC"
print "LinearSVC - Test"

###create pipeline
text_clf = Pipeline([
                     ('vect', vectorizer),
#                      ('tfidf', TfidfTransformer()),
#                      ('clf', MultinomialNB(alpha=alpha)),
                    ('clf', LinearSVC(C=C)),
#                     ("clf", LogisticRegression(fit_intercept=False))
#         ("clf", RandomForestClassifier(n_estimators=50, max_features="auto", criterion="entropy", n_jobs=-1)),
                    ])

###fit training data
text_clf = text_clf.fit(X_train, y_train)

### predict on test data
predicted = text_clf.predict(X_test)

###get performance metrics
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
accuracy = accuracy_score(y_test,predicted)
#         accuracy = np.mean(y_CVtest == predicted)
precision, recall, fscore, sup = precision_recall_fscore_support(y_test, predicted, average='binary', pos_label=0)
print classif, precision, recall, fscore, accuracy# np.mean(predicted == y_test)
###

classif = "randomforest"
print "RandomForest - Test"

###create pipeline
text_clf = Pipeline([
                     ('vect', vectorizer),
#                      ('tfidf', TfidfTransformer()),
#                      ('clf', MultinomialNB(alpha=alpha)),
#                     ('clf', LinearSVC(C=C)),
#                     ("clf", LogisticRegression(fit_intercept=False))
        ("clf", RandomForestClassifier(n_estimators=n_estimators, max_features="auto", criterion="entropy", n_jobs=-1)),
                    ])

###fit training data
text_clf = text_clf.fit(X_train, y_train)

### predict on test data
predicted = text_clf.predict(X_test)

###get performance metrics
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
accuracy = accuracy_score(y_test,predicted)
#         accuracy = np.mean(y_CVtest == predicted)
precision, recall, fscore, sup = precision_recall_fscore_support(y_test, predicted, average='binary', pos_label=0)
print classif, precision, recall, fscore, accuracy# np.mean(predicted == y_test)
###
print "Prediction on Test = DONE!"

Multinomial NB - Test
MNB 0.934336894356 0.976155580609 0.954788553785 0.953776775648
LinearSVC - Test
LinearSVC 0.963107881498 0.971251409245 0.967162503508 0.96702367531
RandomForest - Test
randomforest 0.976786025187 0.948759864713 0.962568985731 0.963105975197
Prediction on Test = DONE!


In [278]:
###print top 5000 features 
import nltk
from sklearn.feature_extraction.text import CountVectorizer

##vectorizer arguments blah!

tokenizer=None#word_tokenize
stop_words=nltk.corpus.stopwords.words("english")#None
stop_words.append('rt')
stop_words.append('com')
stop_words.append('www')
stop_words.append('http')
stop_words.append('https')
stop_words.append('twitter')
ngram_range=(1, 3)
lowercase=True
max_features=5000
binary=False
dtype=np.float64

###create vectorizer
vectorizer = CountVectorizer(decode_error="ignore",
#                                tokenizer=tokenizer,
                               stop_words=stop_words,
                               ngram_range=ngram_range,
                               lowercase=lowercase,
                               binary=binary,
                               dtype=dtype,
                               max_features=max_features)

train_fit = vectorizer.fit_transform(X_train)

In [279]:
vocab = vectorizer.vocabulary_
vocab

{u'fit': 1516,
 u'fix': 1518,
 u'thanks everyone': 4286,
 u'sorted': 4000,
 u'kno': 2417,
 u'knw': 2438,
 u'staring': 4053,
 u'become': 414,
 u'omg love': 3155,
 u'runs': 3690,
 u'nuggets': 3105,
 u'exciting': 1356,
 u'almost done': 189,
 u'think gonna': 4322,
 u'physics': 3300,
 u'camera': 664,
 u'could help': 908,
 u'tweeterfollow add everyone': 4529,
 u'tell annoying': 4255,
 u'effing': 1254,
 u'omg': 3154,
 u'failing': 1384,
 u'joeymcintyre': 2336,
 u'august': 309,
 u'considering': 875,
 u'hour': 2142,
 u'sucks': 4149,
 u'perry': 3278,
 u'coke': 821,
 u'things going': 4314,
 u'andy': 211,
 u'today': 4401,
 u'figure': 1476,
 u'deserve': 1090,
 u'apartment': 246,
 u'time get': 4375,
 u'attention': 306,
 u'shirt': 3837,
 u'iphone': 2271,
 u'tweetdeck': 4522,
 u'lost please': 2661,
 u'yellow': 4956,
 u'wisdom': 4819,
 u'tastes': 4229,
 u'gone': 1774,
 u'gona': 1773,
 u'garden': 1628,
 u'atlanta': 298,
 u'birds': 477,
 u'window': 4808,
 u'felt': 1464,
 u'prepare': 3408,
 u'fool': 1555,


In [280]:
arr = (train_fit.toarray().sum(axis=0))

In [281]:
with open("top5000.txt", "w") as f:
    for key in vocab:
        try:
            f.write(str(key) + ',' + str(arr[vocab[key]]) + "\n")
        except:
            continue

In [272]:
len(arr)

100

In [282]:
stop_words

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 'her',
 'hers',
 'herself',
 'it',
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 '

In [ ]:
X_train